### ISSUE TITLE
HTTPS Certificate Error

### ISSUE THREAD

**Issue by Veyzar** [librenms/librenms.github.io#80]
Hi,

when trying to open https://www.librenms.org/ in Firefox i get the following security warning:

> www.librenms.org uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com Error code: SSL_ERROR_BAD_CERT_DOMAIN

Just wanted to let you know.

**Comment by laf** [comment]
We use github for the site which don't support ssl certs on custom domains.
